ARG CMONGO_VERSION=1.0b-13
ARG CERVER_VERSION=2.0b-40

ARG BUILD_DEPS='ca-certificates libssl-dev gdb'

FROM ermiry/mongoc:builder

ARG BUILD_DEPS
RUN apt-get update && apt-get install -y ${BUILD_DEPS}

# cmongo
ARG CMONGO_VERSION
RUN mkdir /opt/cmongo && cd /opt/cmongo \
    && wget -q --no-check-certificate https://github.com/ermiry-com/cmongo/archive/${CMONGO_VERSION}.zip \
    && unzip ${CMONGO_VERSION}.zip \
    && cd cmongo-${CMONGO_VERSION} \
    && make -j4 && make install

# cerver
ARG CERVER_VERSION
RUN mkdir /opt/cerver && cd /opt/cerver \
    && wget -q https://github.com/ermiry/cerver/archive/${CERVER_VERSION}.zip \
    && unzip ${CERVER_VERSION}.zip \
    && cd cerver-${CERVER_VERSION} \
    && make -j4 && make install

RUN ldconfig

# silverse
WORKDIR /home/silverse

CMD ["/bin/bash"]
